http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  vehicle:
    host: localhost
    paths: '/api/vehicles/*'
  parking:
    host: localhost
    paths: '/parking/*'
  tool:
    host: localhost
    paths: '/api/tools/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  vehicleService:
    url: 'http://localhost:8000'
  parkingService:
    url: 'http://localhost:7000'
  toolService:
    url: 'http://localhost:9000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  vehiclePipeline:
    apiEndpoints:
      - vehicle
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: vehicleService
              changeOrigin: true
  parkingPipeline:
    apiEndpoints:
      - parking
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: parkingService
              changeOrigin: true
  toolPipeline:
    apiEndpoints:
      - tool
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: toolService
              changeOrigin: true
